### ISSUE TITLE
Add labels to the legend

### ISSUE THREAD

**Issue by HealthyPear** [steveberardi/starplot#108]
I do not know if this is really a missing feature, I just could not understand how to do it.

I am creating some markers (with labels) on a MapPlot, adding stars and other object populations, then I call `p.legend()` and I only see e.g. "Star", "Open cluaster" etc... but I do not see my custom objects.

That function does not seem to return anything and I don't think I should have to meddle with matplotlib low-level API to interface with the legend (if it's even possible to interface with MapPlot artists)

**Comment by HealthyPear** [comment]
Ah! the `legend_label` keyword is what I should use. My bad it was explained in the docs...

**Comment by steveberardi** [comment]
no worries! perhaps the `legend_label` shouldn't default to `None` like it does currently -- my thinking there was it's probably more likely that people would plot multiple markers with custom labels but would want them all labelled in the legend the same way.
