### ISSUE TITLE
Canis Minor not defined?

### ISSUE THREAD

**Issue by codingfar** [steveberardi/starplot#110]
I've been trying to create a Map Plot of Canis Minor. When I do:
```
test = Constellation.get(name="Canis Minor")
print(test)
```

I get the output 'None'.

If I try the same for, say, Canis Major (or any other constellation I've tried), I get the correct output, i.e.
`Constellation(iau_id=cma, name=Canis Major, ra=6.95, dec=-23.18)`

This made me suspect that perhaps Canis Minor has been accidentally omitted. (Unless, of course, I'm doing something silly.)

**Environment Details**
- Starplot version: v0.12.2
- Python version: 
- OS: macOS

**Comment by steveberardi** [comment]
ah, thanks for reporting this. Looks like there's a small bug in preparing the constellations reference file: it uses the constellation name as-is [from here](https://github.com/steveberardi/starplot/blob/main/src/starplot/data/constellations.py#L28) (which adds a new line char for some names to help with zenith plots) -- so I just need to remove those new lines before writing the name to the ref file.

Should have a fix out soon 👍
