### ISSUE TITLE
The Fornax constellation's lines include the constellation lines of the constellation Eridanus

### ISSUE THREAD

**Issue by 13-Characters** [steveberardi/starplot#113]
**Describe the bug**
When rendering only the constellation lines of the constellation Fornax, the constellation lines of Eridanus and Fornax both display.

**To Reproduce**
By running these lines of code, I found that the constellation lines for Fornax are not correct.
```python
from starplot import MapPlot, Projection
from starplot import Constellation

# Draco
p = MapPlot(
    projection=Projection.LAMBERT_AZ_EQ_AREA,
    ra_min=1,
    ra_max=5.5,
    dec_min=-60,
    dec_max=5,
)
p.constellations(labels=None, where=[Constellation.constellation_id=='for']) # show Fornax constellation lines only
p.stars(mag=6, labels=None)
p.gridlines(labels=True)
p.export("charts/fornax_chart.png")
```

**Expected behavior**
I expected fornax_chart.png to look like this:
![image](https://github.com/user-attachments/assets/a7578180-dab2-444c-b7df-6eb549f0fa6e)
and I expected eridanus_chart.png to look like this:
![image](https://github.com/user-attachments/assets/f4b2c864-27a7-4e4d-9af6-f37f638a2e2d)

**Screenshots**
Instead, fornax_chart.png looks like this:
<img width="1137" alt="fornax_chart" src="https://github.com/user-attachments/assets/c4d03573-4d63-4beb-a070-69c378ebbc32">
and replacing `p.constellations(labels=None, where=[Constellation.constellation_id=='for'])` with `p.constellations(labels=None, where=[Constellation.constellation_id=='eri'])` results in this image:
<img width="1137" alt="eridanus_chart" src="https://github.com/user-attachments/assets/dbfea1ec-9ce9-4708-86c9-d9e603d43186">

**Environment Details (please complete the following information):**
- Starplot version: v0.12.3
- Python version: 3.10
- Matplotlib version: 3.9.2
- OS: Windows

**Comment by steveberardi** [comment]
ahh, this is a bug in the constellations data. It's happening because the center of Fornax and/or Eridanus are incorrect. I'll add this to the roadmap to fix 👍 For now, a workaround to get the result you're looking for is to use the Constellation's `iau_id` field instead:

```python
p.constellations(
    labels=None,
    where=[Constellation.iau_id == 'for'],
)
```

Thanks for reporting this!
