### ISSUE TITLE
UserWarning: Setting the 'color' property will override the edgecolor or facecolor properties

### ISSUE THREAD

**Issue by HealthyPear** [steveberardi/starplot#114]
Every time I plot a polygon with a specifying the global color I get this warning

> [[......]/starplot/base.py:491](http://localhost:8889/Users/michele/Software/miniforge3/envs/astro/lib/python3.12/site-packages/starplot/base.py#line=490): UserWarning: Setting the 'color' property will override the edgecolor or facecolor properties.
>   patch = patches.Polygon(

When plotting many circles or ellipses this floods quickly the stderr output and can be quite annoying.

Personally I don't thing this warning is needed as this behaviour is clearly explained in the documentation:
https://starplot.dev/reference-styling/#starplot.styles.PolygonStyle

Another solution might be applying a configurable [warning filter](https://docs.python.org/3/library/warnings.html#the-warnings-filter) to plot classes or even [logging](https://docs.python.org/3/tutorial/stdlib2.html#logging).

**Comment by steveberardi** [comment]
hahaha, I was thinking the same thing. There's an undocumented `debug` param to plot constructors that I use to log info when debugging, so I was thinking of enabling all warnings when that's set to `True` -- maybe it's worth a _separate_ parameter though, e.g. `suppress_warnings` (default would be True)
