### ISSUE TITLE
Add legend_label also to circle (and similar objects)

### ISSUE THREAD

**Issue by HealthyPear** [steveberardi/starplot#122]
**Is your feature request related to a problem? Please describe.**
Currently one can only specify a label/legend_label for `marker`.
Of course one can specify en extension and fill color for the marker, but
in this case I need to add a disk which corresponds to a spatial model in the sky,
so markersize does not translate.

**Describe the solution you'd like**

Add label and legend label also to circle / ellipse/ rectangle etc... (I tested only with circle, I guess the others suffer from the same issue)

**Comment by steveberardi** [comment]
I agree this should be supported in some way. It may be a little difficult to do for polygons though (thinking of the case where the polygon is large and complex, like the Milky Way outline -- it'll be difficult to place the label and size it down for the legend). But, I suppose for polygons we could just always plot it as a square or generic "blob" in the legend?

I'll add this to the roadmap. Thanks for the suggestion!!

**Comment by HealthyPear** [comment]
I would propose to keep things simple: squares for rectangles and polygons, circles for circles and ellipses and then we see how the community reacts. I am of course assuming that the user gives different colors to different things, so this simple scenario should be already enough.

**Comment by steveberardi** [comment]
Good thinking (keeping it simple) 👍 

forgot to mention this earlier, but one "hacky" workaround for now is to plot a marker separately for the polygon but make the marker's `alpha=0`

**Comment by steveberardi** [comment]
@HealthyPear not sure if you get notifications when an issue is closed on GitHub, but wanted to let you know I added this feature to the latest release, v0.14. I only added `legend_label` though, cause I wanted to think more about how to handle the `label` styling since there's currently no style that includes a polygon style _and_ a label style.
