### ISSUE TITLE
Really great job

### ISSUE THREAD

**Issue by EsatAkkasoglu** [steveberardi/starplot#49]
You really made the best sky charts I've ever seen. I fully support your project, I'm making an astronomy discord bot and I'm going to use these charts. I'll make sure that every time you create a chart, the name of the library is mentioned under it :)

**Comment by steveberardi** [comment]
@EsatAkkasoglu thanks so much for your kind words! Let me know when your astronomy bot is up and running, I'd love to check it out.

**Comment by steveberardi** [comment]
@EsatAkkasoglu hey! I wanted to let you know I created a discord server for starplot, where I'm hoping users and developers of starplot can get together and share thoughts/ideas/feedback and just general astronomy chat :) I remember you mentioning you're building a discord bot so it'd be great to see you (or the bot! haha) on the starplot server! Here's the invite: https://discord.gg/bwazdyD7
