### ISSUE TITLE
Could you please consider to add date/time and lon/lat on the chart?

### ISSUE THREAD

**Issue by kinoshitadaisuke** [steveberardi/starplot#5]
Hello,

This is a nice piece of work.

Could you please consider to add date/time and lon/lat on the chart?

And, could you also consider to place files "de421.bsp", "hip_main.dat", and "constellationship.fab" at the directory ~/.starplot?
Currently, these files are placed at the currently working directory.
If I try to make a chart at a different directory, these files are downloaded again.

thank you,

Daisuke

**Comment by steveberardi** [comment]
Hi Daisuke,

Thanks for your interest and suggestions! I like the idea of adding the date/time and location on the chart — I'll put that on my todo list :)

Regarding the data files (`de421.bsp`, etc), I'll probably include them (or a subset of them) in the package in future releases to help alleviate data management issues.

Steve

**Comment by steveberardi** [comment]
Hi Daisuke,

I just released a new version today (0.2.2) that includes an option for plotting the date/time/location on the chart.

Also created some documentation at https://starplot.dev/

Steve
