### ISSUE TITLE
Customize cardinal point labels

### ISSUE THREAD

**Issue by ricardo-dlc** [steveberardi/starplot#77]
I was wondering if this is possible. The library offers an option to customize the labels for moon or sun for example, but what about the cardinal points? I want to put the labels in my local language. In fact, the only one that varies is the W label.

N: N(orte)
S: S(ur)
E: E(ste)
W: O(este)

**Comment by steveberardi** [comment]
Currently, there is no built-in way to override the cardinal direction labels on zenith plots, but you bring up a great point! I want Starplot to allow overriding all labels, so I'll put this on the roadmap for the next version.

Thanks for your feedback!

**Comment by steveberardi** [comment]
This is now supported in the latest version (v0.11.0) -- [see the docs on the `horizon` function for details](https://starplot.dev/reference-mapplot/#starplot.MapPlot.horizon)

**Comment by ricardo-dlc** [comment]
Amazing!
