### ISSUE TITLE
The discord link doesn't work

### ISSUE THREAD

**Issue by hemisemidemipresent** [steveberardi/starplot#81]
**Describe the bug**
> Chat with other starplotters on our Discord server:
> https://discord.gg/bwazdyD7

The discord link doesn't work

**To Reproduce**
click on the link while signed in into a discord account that is not already in the server

**Expected behavior**
I get redirected to the discord server

**Screenshots**
![image](https://github.com/steveberardi/starplot/assets/57880110/e2974cb2-d8cf-469e-9a6a-37575cceba66)

**Environment Details (please complete the following information):**
- OS: Windows (though I installed starplot on linux)

**Additional context**
none

**Comment by steveberardi** [comment]
oh wow, thanks for reporting this. Might help explain why we haven't had any new members on discord for awhile 😆 

Discord must've updated the way their invites work. Anyway, here's a new link to join: https://discord.gg/9rMpJE2E

Updating the docs now.

Thanks again!
