### ISSUE TITLE
unable to filter based on ngc in where clause in plot.dsos()

### ISSUE THREAD

**Issue by hemisemidemipresent** [steveberardi/starplot#97]
**Describe the bug**
So I wanted to plot all NGC DSOs via `DSO.ngc.is_not_null()`

```py
from starplot import Star, DSO, MapPlot, Projection
from starplot.styles import PlotStyle, extensions

style = PlotStyle().extend(
    extensions.BLUE_LIGHT,
    extensions.MAP,
)
p = MapPlot(
    projection=Projection.MILLER,  # specify a non-perspective projection
    ra_min=0,  # limit the map to a specific area
    ra_max=8,
    dec_min=-40,
    dec_max=65,
    style=style,
    resolution=3600,
    hide_colliding_labels=False
)
p.gridlines() # add gridlines

p.stars(
    where=[Star.magnitude < 6],
    where_labels=[ (Star.magnitude < 3)],
    bayer_labels=True
)

p.dsos(
    where=[DSO.ngc.is_not_null()],
)

p.constellations()
p.constellation_borders()
p.milky_way()
p.celestial_equator()
p.ecliptic()

p.export("test.png", padding=0.2, transparent=True)
```

However, I get no DSOs:

![image](https://github.com/user-attachments/assets/3f051d14-3ed4-4578-b6d8-929ac7e18311)

For fun, I tried inverting it to find all objects *without* an NGC code:

```py
p.dsos(
    where=[DSO.ngc.is_null()],
)
```
And I got plenty of NGCs:

![image](https://github.com/user-attachments/assets/bac6c448-cb89-42ef-ab5b-75c915cacdca)

**Environment Details (please complete the following information):**
- Starplot version: v0.11.3
- Python version: 3.11.8
- Matplotlib version: 3.9.2

**Additional context**
I'm not sure what is going on since the dso object seems to have `.ngc`:
```py
>>> from starplot import DSO
>>> d = DSO.get(ngc='2264')
>>> d
DSO(name=NGC2264, magnitude=3.9)
>>> d.ngc
'2264'
```

**Comment by steveberardi** [comment]
oh wow! looks like this is happening cause the NGC id is not passed here -- https://github.com/steveberardi/starplot/blob/main/src/starplot/plotters/dsos.py#L25-L39

I'll get a fixed release out tomorrow. Thanks for reporting this and sharing the code/environment details!

**Comment by steveberardi** [comment]
v0.11.4 going out now, which fixes this issue
